# Generated by Django 3.0.6 on 2020-05-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'managed': True, 'ordering': ('created_at', 'updated_at'), 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
